# Generated by Django 4.0 on 2021-12-12 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=40, unique=True)),
                ('password', models.CharField(max_length=300)),
                ('email_address', models.EmailField(max_length=150, unique=True)),
                ('user_uuid', models.CharField(max_length=36, primary_key=True, serialize=False)),
            ],
        ),
    ]
