# Generated by Django 4.0 on 2021-12-12 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoList', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_uuid', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('task_title', models.CharField(max_length=200)),
                ('task_description', models.TextField(max_length=800, null=True)),
                ('task_done', models.BooleanField(default=False)),
                ('task_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ToDoList.user')),
            ],
        ),
    ]
